// <auto-generated />
namespace GUI_Group_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeprimarykey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeprimarykey));
        
        string IMigrationMetadata.Id
        {
            get { return "202112160550270_change primary key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
